### ISSUE TITLE
Fix initialization bug where marker initially pans to far left of screen when first clicked

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#15] opened 2016-04-15 20:08 UTC
Fix initialization bug where marker initially pans to far left of screen when first clicked

**Comment by wpsmort** [comment] 2016-06-15 21:22
There may be code for this in SimpleMap v2.5.

**Comment by michaeltorbert** [comment] 2017-02-05 05:44
Is this still happening? I can't reproduce it.

**Comment by wpsmort** [comment] 2017-03-21 19:26
@arnaudbroes This may be in reference to the fact that the map pans slightly to the left when you click on a pin because the map bubble is wider and so the map has to pan to the left in order for the entire bubble to show.  You may want to test back through versions of SimpleMap to see if this got worse at some point.  I know we increased the width of the bubble at some point so maybe this started when that happened.

**Comment by wpsmort** [comment] 2017-03-23 22:19
I tested back to v2.4.5 and found that this was introduced in v2.4.7 when we changed to InfoBox for the map bubble.  Making the map bubble less wide would fix this issue or we could leave this until we come up with a solution for #21.

I personally vote for the latter as nobody has reported this as a bug and it doesn't interfere with the operation of the map.  I recommend we close this issue.

**Comment by michaeltorbert** [comment] 2017-03-23 22:30
Agreed.

**Closed by michaeltorbert** 2017-03-23 22:30 UTC
Labels: Bug, Wontfix
