### ISSUE TITLE
Adding country to search field

### ISSUE THREAD

**Issue by bjornproductions** [semperfiwebdesign/simplemap#239] opened 2017-04-14 06:47 UTC
Currently when searching for a location, it only shows street, city, state, zip.

How can I add 'Country' into the search settings?

Here is a link to my client's website: http://www.hamskeaarchery.com/dealers/

**Comment by wpsmort** [comment] 2017-04-17 20:26
This is a duplicate of #14 which is currently in development.

**Closed by wpsmort** 2017-04-17 20:26 UTC
