### ISSUE TITLE
Import screen doesn't fit within Dashboard space

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#133] opened 2017-01-21 00:56 UTC
As seen here:

![image](https://cloud.githubusercontent.com/assets/18156697/22170361/e787b316-df7c-11e6-8fd8-56e65cb7e33d.png)

**Not responsive as well.

**Comment by michaeltorbert** [comment] 2017-01-21 00:57
@arnaudbroes  Yeah this needs to be completely redone for desktop too

**Comment by arnaudbroes** [comment] 2017-01-21 00:58
Yep I meant desktop, already changed title.

**Comment by wpsmort** [comment] 2017-03-20 22:11
This is a duplicate of #125

**Closed by wpsmort** 2017-03-20 22:11 UTC
Labels: UX
